### ISSUE TITLE
Is it possible to pre-populate the search ?

### ISSUE THREAD

**Issue by siddhartham** [CultureHQ/react-tenor#249]
Is it possible to pre-populate the search ?
Like whne the component loads can pass some props like

> <Tenor token="xxxxx" search={'happy'} onSelect={result => console.log(result)} />

**Comment by kddeisz** [comment]
Not at the moment, but one second

**Comment by kddeisz** [comment]
Yeah v1.3.0 has an `initialSearch` property now.

**Comment by siddhartham** [comment]
I upgraded to 1.3, did not work, what I am doing wrong ?
<Tenor token="XXXX" initialSearch={'happy'} onSelect={addTenor.bind(this)} />

also, don't see it here
https://github.com/CultureHQ/react-tenor/blob/v1.3.0/dist/Tenor.js

**Comment by kddeisz** [comment]
Ahh gosh I'm sorry I've been using the es6 source in my app so didn't notice. I just pushed 1.3.1 with the rebuild dist.

**Comment by siddhartham** [comment]
thanks for the quick fix :)

**Comment by kddeisz** [comment]
Thanks for checking this out/using it! Let me know if there are any other things that could help you out. I like this one a lot as a side project so happy to continue development.
