### ISSUE TITLE
Possible to use tenor trending as default ?

### ISSUE THREAD

**Issue by siddhartham** [CultureHQ/react-tenor#277]
Possible to use tenor trending as default?
i.e. the gifs you see here
https://tenor.com

**Comment by kddeisz** [comment]
Yeah definitely! Looks like they provide the endpoint https://tenor.com/gifapi/documentation#endpoints-trendinggifs. I don't have the capacity to build it at the moment, but would love to see a PR for it!

**Comment by kddeisz** [comment]
This is now available on master and will be part of the next release
