### ISSUE TITLE
Set search limit

### ISSUE THREAD

**Issue by jsonjuri** [CultureHQ/react-tenor#455]
Can you add adjusting the limit on the Tenor element?

Like: `<Tenor limit="24">`

**Comment by kddeisz** [comment]
Yup! I've added it (though make sure it's a number, as in `<Tenor limit={24} />`). I'll release it momentarily as `v2.2.0`.

**Comment by jsonjuri** [comment]
> Yup! I've added it (though make sure it's a number, as in `<Tenor limit={24} />`). I'll release it momentarily as `v2.2.0`.

Great, thanks!
